[package]
name = "logger"
version = "0.1.1"
edition = "2021"

[dependencies]
chrono = "0.4.38"
colored = "2.1.0"
libc = "0.2.162"
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
serde_with = "3.11.0"

[lib]
crate-type = ["dylib"]
